### PR TITLE
add some refactor and writ test for FilePath analyzer

### PR DESCRIPTION
**Pull request by hAz5**

### CODE REVIEW

**Comment by imanghafoori1** [comment]
please do not apply any return type in the code.
Remove :Finder
since the have a performance hit and we want to be fast

**Comment by hAz5** [comment]
@imanghafoori1 I removed return types

**Comment by imanghafoori1** [comment]
also type hints:
public static function getAllPhpFiles(string $path)

**Comment by hAz5** [comment]
@imanghafoori1 I did it

**Comment by imanghafoori1** [comment]
well done.

**Pull request merged**
