### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by innoflash**
This aims to fix this suggestion https://github.com/imanghafoori1/laravel-microscope/issues/40

Had to go through other files too and make a few ammendments

### CODE REVIEW

**Comment by imanghafoori1** [comment]
Please be careful about unnecessary changes due to reformatting of your IDE
Like the $count property on the error printer. 
And also try to squash your commits into one or two would be better


Thanks a lot

**Comment by innoflash** [comment]
Cool i will squash them. I wanted to make it easy for you to read the changes i have made. One mega commit might be difficult to inspect if i touched more than one file

**Comment by imanghafoori1** [comment]
Could you please remake this PR according to the latest changes of the code?

**Comment by innoflash** [comment]
Copy that, It should be up now

**Pull request merged**
